<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.2" />
    <!-- xUnit support -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anakin-Analytics\Anakin-Analytics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="strings\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="GroundTruth\amazonReviewSnippets_GroundTruth_vader-3.3.2.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="GroundTruth\amazonReviewSnippets_GroundTruth_vader.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="GroundTruth\movieReviewSnippets_GroundTruth_vader-3.3.2.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="GroundTruth\movieReviewSnippets_GroundTruth_vader.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="GroundTruth\nytEditorialSnippets_GroundTruth_vader-3.3.2.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="GroundTruth\nytEditorialSnippets_GroundTruth_vader.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="GroundTruth\tweets_GroundTruth_vader-3.3.2.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="GroundTruth\tweets_GroundTruth_vader.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="strings\en-gb.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="strings\en-US.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="strings\es-ES.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="strings\fr-FR.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
